import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'country_catalog.freezed.dart';
part 'country_catalog.g.dart';

@freezed
abstract class Country with _$Country {
  const factory Country({
    @required @JsonKey() String numCode,
    @required @JsonKey() String alphaCode2,
    @required @JsonKey() String alphaCode3,
    @required @JsonKey() String name,
    @required @JsonKey() String nationality,
    @required @JsonKey() String code,
    @Default(false) @JsonKey(defaultValue: false) bool stripe,
  }) = _Country;

  factory Country.fromJson(Map<String, dynamic> json) => _$CountryFromJson(json);
  static AssetImage imageOf(Country country, {String package}) =>
      AssetImage('flags/${country.alphaCode2.toLowerCase()}.png', package: package);
}

class CountryConverter implements JsonConverter<Country, String> {
  const CountryConverter();

  @override
  Country fromJson(String json) => json != null ? CountryCatalog.fromAlphaCode(json) : null;

  @override
  String toJson(Country object) => object?.alphaCode2;
}

/// A country catalog used troughout my apps.
///
/// NOTE: I noticed some countries missing, like Canada.
class CountryCatalog {
  static List<Country> countries = _kCountries.values.toList(growable: false)..sort((a, b) => a.name.compareTo(b.name));
  static List<Country> stripeSupportedCountries = countries.where((country) => country.stripe).toList(growable: false);

  static Country fromCountryCode(String code) => _kCountriesByCountryCode[code];
  static Country fromAlphaCode(String code) => _kCountries[code];

  static const _kCountries = <String, Country>{
    'HM': Country(
      numCode: '334',
      alphaCode2: 'HM',
      alphaCode3: 'HMD',
      name: 'Heard Island and McDonald Islands',
      nationality: 'Heard Island or McDonald Islands',
      code: '+0',
    ),
    'US': Country(
      numCode: '840',
      alphaCode2: 'US',
      alphaCode3: 'USA',
      name: 'United States of America',
      nationality: 'American',
      code: '+1',
      stripe: true,
    ),
    'CA': Country(
      numCode: '124',
      alphaCode2: 'CA',
      alphaCode3: 'CAN',
      name: 'Canada',
      nationality: 'Canadian',
      code: '+1',
      stripe: true,
    ),
    'NZ': Country(
      numCode: '554',
      alphaCode2: 'NZ',
      alphaCode3: 'NZL',
      name: 'New Zealand',
      nationality: 'New Zealander',
      code: '+64',
      stripe: true,
    ),
    'NO': Country(
      numCode: '578',
      alphaCode2: 'NO',
      alphaCode3: 'NOR',
      name: 'Norway',
      nationality: 'Norwegian',
      code: '+47',
      stripe: true,
    ),
    'RU': Country(
      numCode: '643',
      alphaCode2: 'RU',
      alphaCode3: 'RUS',
      name: 'Russian Federation',
      nationality: 'Russian',
      code: '+7',
    ),
    'EG': Country(
      numCode: '818',
      alphaCode2: 'EG',
      alphaCode3: 'EGY',
      name: 'Egypt',
      nationality: 'Egyptian',
      code: '+20',
    ),
    'ZA': Country(
      numCode: '710',
      alphaCode2: 'ZA',
      alphaCode3: 'ZAF',
      name: 'South Africa',
      nationality: 'South African',
      code: '+27',
    ),
    'GR': Country(
      numCode: '300',
      alphaCode2: 'GR',
      alphaCode3: 'GRC',
      name: 'Greece',
      nationality: 'Greek, Hellenic',
      code: '+30',
      stripe: true,
    ),
    'NL': Country(
      numCode: '528',
      alphaCode2: 'NL',
      alphaCode3: 'NLD',
      name: 'Netherlands',
      nationality: 'Dutch, Netherlandic',
      code: '+31',
      stripe: true,
    ),
    'BE': Country(
      numCode: '56',
      alphaCode2: 'BE',
      alphaCode3: 'BEL',
      name: 'Belgium',
      nationality: 'Belgian',
      code: '+32',
      stripe: true,
    ),
    'FR': Country(
      numCode: '250',
      alphaCode2: 'FR',
      alphaCode3: 'FRA',
      name: 'France',
      nationality: 'French',
      code: '+33',
      stripe: true,
    ),
    'ES': Country(
      numCode: '724',
      alphaCode2: 'ES',
      alphaCode3: 'ESP',
      name: 'Spain',
      nationality: 'Spanish',
      code: '+34',
      stripe: true,
    ),
    'HU': Country(
      numCode: '348',
      alphaCode2: 'HU',
      alphaCode3: 'HUN',
      name: 'Hungary',
      nationality: 'Hungarian, Magyar',
      code: '+36',
      stripe: true,
    ),
    'IT': Country(
      numCode: '380',
      alphaCode2: 'IT',
      alphaCode3: 'ITA',
      name: 'Italy',
      nationality: 'Italian',
      code: '+39',
      stripe: true,
    ),
    'RO': Country(
      numCode: '642',
      alphaCode2: 'RO',
      alphaCode3: 'ROU',
      name: 'Romania',
      nationality: 'Romanian',
      code: '+40',
      stripe: true,
    ),
    'CH': Country(
      numCode: '756',
      alphaCode2: 'CH',
      alphaCode3: 'CHE',
      name: 'Switzerland',
      nationality: 'Swiss',
      code: '+41',
      stripe: true,
    ),
    'AT': Country(
      numCode: '40',
      alphaCode2: 'AT',
      alphaCode3: 'AUT',
      name: 'Austria',
      nationality: 'Austrian',
      code: '+43',
      stripe: true,
    ),
    'GB': Country(
      numCode: '826',
      alphaCode2: 'GB',
      alphaCode3: 'GBR',
      name: 'United Kingdom of Great Britain and Northern Ireland',
      nationality: 'British, UK',
      code: '+44',
      stripe: true,
    ),
    'DK': Country(
      numCode: '208',
      alphaCode2: 'DK',
      alphaCode3: 'DNK',
      name: 'Denmark',
      nationality: 'Danish',
      code: '+45',
      stripe: true,
    ),
    'SE': Country(
      numCode: '752',
      alphaCode2: 'SE',
      alphaCode3: 'SWE',
      name: 'Sweden',
      nationality: 'Swedish',
      code: '+46',
      stripe: true,
    ),
    'SJ': Country(
      numCode: '744',
      alphaCode2: 'SJ',
      alphaCode3: 'SJM',
      name: 'Svalbard and Jan Mayen',
      nationality: 'Svalbard',
      code: '+47',
    ),
    'PL': Country(
      numCode: '616',
      alphaCode2: 'PL',
      alphaCode3: 'POL',
      name: 'Poland',
      nationality: 'Polish',
      code: '+48',
      stripe: true,
    ),
    'DE': Country(
      numCode: '276',
      alphaCode2: 'DE',
      alphaCode3: 'DEU',
      name: 'Germany',
      nationality: 'German',
      code: '+49',
      stripe: true,
    ),
    'PE': Country(
      numCode: '604',
      alphaCode2: 'PE',
      alphaCode3: 'PER',
      name: 'Peru',
      nationality: 'Peruvian',
      code: '+51',
    ),
    'MX': Country(
      numCode: '484',
      alphaCode2: 'MX',
      alphaCode3: 'MEX',
      name: 'Mexico',
      nationality: 'Mexican',
      code: '+52',
      stripe: true,
    ),
    'CU': Country(
      numCode: '192',
      alphaCode2: 'CU',
      alphaCode3: 'CUB',
      name: 'Cuba',
      nationality: 'Cuban',
      code: '+53',
    ),
    'AR': Country(
      numCode: '32',
      alphaCode2: 'AR',
      alphaCode3: 'ARG',
      name: 'Argentina',
      nationality: 'Argentine',
      code: '+54',
    ),
    'BR': Country(
      numCode: '76',
      alphaCode2: 'BR',
      alphaCode3: 'BRA',
      name: 'Brazil',
      nationality: 'Brazilian',
      code: '+55',
      stripe: true,
    ),
    'CL': Country(
      numCode: '152',
      alphaCode2: 'CL',
      alphaCode3: 'CHL',
      name: 'Chile',
      nationality: 'Chilean',
      code: '+56',
    ),
    'CO': Country(
      numCode: '170',
      alphaCode2: 'CO',
      alphaCode3: 'COL',
      name: 'Colombia',
      nationality: 'Colombian',
      code: '+57',
    ),
    'VE': Country(
      numCode: '862',
      alphaCode2: 'VE',
      alphaCode3: 'VEN',
      name: 'Venezuela (Bolivarian Republic of)',
      nationality: 'Venezuelan',
      code: '+58',
    ),
    'MY': Country(
      numCode: '458',
      alphaCode2: 'MY',
      alphaCode3: 'MYS',
      name: 'Malaysia',
      nationality: 'Malaysian',
      code: '+60',
    ),
    'CC': Country(
      numCode: '166',
      alphaCode2: 'CC',
      alphaCode3: 'CCK',
      name: 'Cocos (Keeling) Islands',
      nationality: 'Cocos Island',
      code: '+61',
    ),
    'ID': Country(
      numCode: '360',
      alphaCode2: 'ID',
      alphaCode3: 'IDN',
      name: 'Indonesia',
      nationality: 'Indonesian',
      code: '+62',
    ),
    'PH': Country(
      numCode: '608',
      alphaCode2: 'PH',
      alphaCode3: 'PHL',
      name: 'Philippines',
      nationality: 'Philippine, Filipino',
      code: '+63',
    ),
    'PN': Country(
      numCode: '612',
      alphaCode2: 'PN',
      alphaCode3: 'PCN',
      name: 'Pitcairn',
      nationality: 'Pitcairn Island',
      code: '+64',
    ),
    'SG': Country(
      numCode: '702',
      alphaCode2: 'SG',
      alphaCode3: 'SGP',
      name: 'Singapore',
      nationality: 'Singaporean',
      code: '+65',
      stripe: true,
    ),
    'TH': Country(
      numCode: '764',
      alphaCode2: 'TH',
      alphaCode3: 'THA',
      name: 'Thailand',
      nationality: 'Thai',
      code: '+66',
    ),
    'JP': Country(
      numCode: '392',
      alphaCode2: 'JP',
      alphaCode3: 'JPN',
      name: 'Japan',
      nationality: 'Japanese',
      code: '+81',
      stripe: true,
    ),
    'KR': Country(
      numCode: '410',
      alphaCode2: 'KR',
      alphaCode3: 'KOR',
      name: 'Korea (Republic of)',
      nationality: 'South Korean',
      code: '+82',
    ),
    'VN': Country(
      numCode: '704',
      alphaCode2: 'VN',
      alphaCode3: 'VNM',
      name: 'Vietnam',
      nationality: 'Vietnamese',
      code: '+84',
    ),
    'CN': Country(
      numCode: '156',
      alphaCode2: 'CN',
      alphaCode3: 'CHN',
      name: 'China',
      nationality: 'Chinese',
      code: '+86',
    ),
    'TR': Country(
      numCode: '792',
      alphaCode2: 'TR',
      alphaCode3: 'TUR',
      name: 'Turkey',
      nationality: 'Turkish',
      code: '+90',
    ),
    'IN': Country(
      numCode: '356',
      alphaCode2: 'IN',
      alphaCode3: 'IND',
      name: 'India',
      nationality: 'Indian',
      code: '+91',
      stripe: true,
    ),
    'PK': Country(
      numCode: '586',
      alphaCode2: 'PK',
      alphaCode3: 'PAK',
      name: 'Pakistan',
      nationality: 'Pakistani',
      code: '+92',
    ),
    'AF': Country(
      numCode: '4',
      alphaCode2: 'AF',
      alphaCode3: 'AFG',
      name: 'Afghanistan',
      nationality: 'Afghan',
      code: '+93',
    ),
    'LK': Country(
      numCode: '144',
      alphaCode2: 'LK',
      alphaCode3: 'LKA',
      name: 'Sri Lanka',
      nationality: 'Sri Lankan',
      code: '+94',
    ),
    'MM': Country(
      numCode: '104',
      alphaCode2: 'MM',
      alphaCode3: 'MMR',
      name: 'Myanmar',
      nationality: 'Burmese',
      code: '+95',
    ),
    'IR': Country(
      numCode: '364',
      alphaCode2: 'IR',
      alphaCode3: 'IRN',
      name: 'Iran',
      nationality: 'Iranian, Persian',
      code: '+98',
    ),
    'SS': Country(
      numCode: '728',
      alphaCode2: 'SS',
      alphaCode3: 'SSD',
      name: 'South Sudan',
      nationality: 'South Sudanese',
      code: '+211',
    ),
    'MA': Country(
      numCode: '504',
      alphaCode2: 'MA',
      alphaCode3: 'MAR',
      name: 'Morocco',
      nationality: 'Moroccan',
      code: '+212',
    ),
    'DZ': Country(
      numCode: '12',
      alphaCode2: 'DZ',
      alphaCode3: 'DZA',
      name: 'Algeria',
      nationality: 'Algerian',
      code: '+213',
    ),
    'TN': Country(
      numCode: '788',
      alphaCode2: 'TN',
      alphaCode3: 'TUN',
      name: 'Tunisia',
      nationality: 'Tunisian',
      code: '+216',
    ),
    'LY': Country(
      numCode: '434',
      alphaCode2: 'LY',
      alphaCode3: 'LBY',
      name: 'Libya',
      nationality: 'Libyan',
      code: '+218',
    ),
    'GM': Country(
      numCode: '270',
      alphaCode2: 'GM',
      alphaCode3: 'GMB',
      name: 'Gambia',
      nationality: 'Gambian',
      code: '+220',
    ),
    'SN': Country(
      numCode: '686',
      alphaCode2: 'SN',
      alphaCode3: 'SEN',
      name: 'Senegal',
      nationality: 'Senegalese',
      code: '+221',
    ),
    'MR': Country(
      numCode: '478',
      alphaCode2: 'MR',
      alphaCode3: 'MRT',
      name: 'Mauritania',
      nationality: 'Mauritanian',
      code: '+222',
    ),
    'ML': Country(
      numCode: '466',
      alphaCode2: 'ML',
      alphaCode3: 'MLI',
      name: 'Mali',
      nationality: 'Malian, Malinese',
      code: '+223',
    ),
    'GN': Country(
      numCode: '324',
      alphaCode2: 'GN',
      alphaCode3: 'GIN',
      name: 'Guinea',
      nationality: 'Guinean',
      code: '+224',
    ),
    'CI': Country(
      numCode: '384',
      alphaCode2: 'CI',
      alphaCode3: 'CIV',
      name: 'Côte d\'Ivoire',
      nationality: 'Ivorian',
      code: '+225',
    ),
    'BF': Country(
      numCode: '854',
      alphaCode2: 'BF',
      alphaCode3: 'BFA',
      name: 'Burkina Faso',
      nationality: 'Burkinabé',
      code: '+226',
    ),
    'NE': Country(
      numCode: '562',
      alphaCode2: 'NE',
      alphaCode3: 'NER',
      name: 'Niger',
      nationality: 'Nigerien',
      code: '+227',
    ),
    'TG': Country(
      numCode: '768',
      alphaCode2: 'TG',
      alphaCode3: 'TGO',
      name: 'Togo',
      nationality: 'Togolese',
      code: '+228',
    ),
    'BJ': Country(
      numCode: '204',
      alphaCode2: 'BJ',
      alphaCode3: 'BEN',
      name: 'Benin',
      nationality: 'Beninese, Beninois',
      code: '+229',
    ),
    'MU': Country(
      numCode: '480',
      alphaCode2: 'MU',
      alphaCode3: 'MUS',
      name: 'Mauritius',
      nationality: 'Mauritian',
      code: '+230',
    ),
    'LR': Country(
      numCode: '430',
      alphaCode2: 'LR',
      alphaCode3: 'LBR',
      name: 'Liberia',
      nationality: 'Liberian',
      code: '+231',
    ),
    'SL': Country(
      numCode: '694',
      alphaCode2: 'SL',
      alphaCode3: 'SLE',
      name: 'Sierra Leone',
      nationality: 'Sierra Leonean',
      code: '+232',
    ),
    'GH': Country(
      numCode: '288',
      alphaCode2: 'GH',
      alphaCode3: 'GHA',
      name: 'Ghana',
      nationality: 'Ghanaian',
      code: '+233',
    ),
    'NG': Country(
      numCode: '566',
      alphaCode2: 'NG',
      alphaCode3: 'NGA',
      name: 'Nigeria',
      nationality: 'Nigerian',
      code: '+234',
    ),
    'TD': Country(
      numCode: '148',
      alphaCode2: 'TD',
      alphaCode3: 'TCD',
      name: 'Chad',
      nationality: 'Chadian',
      code: '+235',
    ),
    'CF': Country(
      numCode: '140',
      alphaCode2: 'CF',
      alphaCode3: 'CAF',
      name: 'Central African Republic',
      nationality: 'Central African',
      code: '+236',
    ),
    'CM': Country(
      numCode: '120',
      alphaCode2: 'CM',
      alphaCode3: 'CMR',
      name: 'Cameroon',
      nationality: 'Cameroonian',
      code: '+237',
    ),
    'CV': Country(
      numCode: '132',
      alphaCode2: 'CV',
      alphaCode3: 'CPV',
      name: 'Cabo Verde',
      nationality: 'Cabo Verdean',
      code: '+238',
    ),
    'ST': Country(
      numCode: '678',
      alphaCode2: 'ST',
      alphaCode3: 'STP',
      name: 'Sao Tome and Principe',
      nationality: 'São Toméan',
      code: '+239',
    ),
    'GQ': Country(
      numCode: '226',
      alphaCode2: 'GQ',
      alphaCode3: 'GNQ',
      name: 'Equatorial Guinea',
      nationality: 'Equatorial Guinean, Equatoguinean',
      code: '+240',
    ),
    'GA': Country(
      numCode: '266',
      alphaCode2: 'GA',
      alphaCode3: 'GAB',
      name: 'Gabon',
      nationality: 'Gabonese',
      code: '+241',
    ),
    'CG': Country(
      numCode: '178',
      alphaCode2: 'CG',
      alphaCode3: 'COG',
      name: 'Congo (Republic of the)',
      nationality: 'Congolese',
      code: '+242',
    ),
    'CD': Country(
      numCode: '180',
      alphaCode2: 'CD',
      alphaCode3: 'COD',
      name: 'Congo (Democratic Republic of the)',
      nationality: 'Congolese',
      code: '+243',
    ),
    'AO': Country(
      numCode: '24',
      alphaCode2: 'AO',
      alphaCode3: 'AGO',
      name: 'Angola',
      nationality: 'Angolan',
      code: '+244',
    ),
    'GW': Country(
      numCode: '624',
      alphaCode2: 'GW',
      alphaCode3: 'GNB',
      name: 'Guinea-Bissau',
      nationality: 'Bissau-Guinean',
      code: '+245',
    ),
    'IO': Country(
      numCode: '86',
      alphaCode2: 'IO',
      alphaCode3: 'IOT',
      name: 'British Indian Ocean Territory',
      nationality: 'BIOT',
      code: '+246',
    ),
    'SC': Country(
      numCode: '690',
      alphaCode2: 'SC',
      alphaCode3: 'SYC',
      name: 'Seychelles',
      nationality: 'Seychellois',
      code: '+248',
    ),
    'SD': Country(
      numCode: '729',
      alphaCode2: 'SD',
      alphaCode3: 'SDN',
      name: 'Sudan',
      nationality: 'Sudanese',
      code: '+249',
    ),
    'RW': Country(
      numCode: '646',
      alphaCode2: 'RW',
      alphaCode3: 'RWA',
      name: 'Rwanda',
      nationality: 'Rwandan',
      code: '+250',
    ),
    'ET': Country(
      numCode: '231',
      alphaCode2: 'ET',
      alphaCode3: 'ETH',
      name: 'Ethiopia',
      nationality: 'Ethiopian',
      code: '+251',
    ),
    'SO': Country(
      numCode: '706',
      alphaCode2: 'SO',
      alphaCode3: 'SOM',
      name: 'Somalia',
      nationality: 'Somali, Somalian',
      code: '+252',
    ),
    'DJ': Country(
      numCode: '262',
      alphaCode2: 'DJ',
      alphaCode3: 'DJI',
      name: 'Djibouti',
      nationality: 'Djiboutian',
      code: '+253',
    ),
    'KE': Country(
      numCode: '404',
      alphaCode2: 'KE',
      alphaCode3: 'KEN',
      name: 'Kenya',
      nationality: 'Kenyan',
      code: '+254',
    ),
    'TZ': Country(
      numCode: '834',
      alphaCode2: 'TZ',
      alphaCode3: 'TZA',
      name: 'Tanzania, United Republic of',
      nationality: 'Tanzanian',
      code: '+255',
    ),
    'UG': Country(
      numCode: '800',
      alphaCode2: 'UG',
      alphaCode3: 'UGA',
      name: 'Uganda',
      nationality: 'Ugandan',
      code: '+256',
    ),
    'BI': Country(
      numCode: '108',
      alphaCode2: 'BI',
      alphaCode3: 'BDI',
      name: 'Burundi',
      nationality: 'Burundian',
      code: '+257',
    ),
    'MZ': Country(
      numCode: '508',
      alphaCode2: 'MZ',
      alphaCode3: 'MOZ',
      name: 'Mozambique',
      nationality: 'Mozambican',
      code: '+258',
    ),
    'ZM': Country(
      numCode: '894',
      alphaCode2: 'ZM',
      alphaCode3: 'ZMB',
      name: 'Zambia',
      nationality: 'Zambian',
      code: '+260',
    ),
    'MG': Country(
      numCode: '450',
      alphaCode2: 'MG',
      alphaCode3: 'MDG',
      name: 'Madagascar',
      nationality: 'Malagasy',
      code: '+261',
    ),
    'RE': Country(
      numCode: '638',
      alphaCode2: 'RE',
      alphaCode3: 'REU',
      name: 'Réunion',
      nationality: 'Réunionese, Réunionnais',
      code: '+262',
    ),
    'ZW': Country(
      numCode: '716',
      alphaCode2: 'ZW',
      alphaCode3: 'ZWE',
      name: 'Zimbabwe',
      nationality: 'Zimbabwean',
      code: '+263',
    ),
    'NA': Country(
      numCode: '516',
      alphaCode2: 'NA',
      alphaCode3: 'NAM',
      name: 'Namibia',
      nationality: 'Namibian',
      code: '+264',
    ),
    'MW': Country(
      numCode: '454',
      alphaCode2: 'MW',
      alphaCode3: 'MWI',
      name: 'Malawi',
      nationality: 'Malawian',
      code: '+265',
    ),
    'LS': Country(
      numCode: '426',
      alphaCode2: 'LS',
      alphaCode3: 'LSO',
      name: 'Lesotho',
      nationality: 'Basotho',
      code: '+266',
    ),
    'BW': Country(
      numCode: '72',
      alphaCode2: 'BW',
      alphaCode3: 'BWA',
      name: 'Botswana',
      nationality: 'Motswana, Botswanan',
      code: '+267',
    ),
    'SZ': Country(
      numCode: '748',
      alphaCode2: 'SZ',
      alphaCode3: 'SWZ',
      name: 'Swaziland',
      nationality: 'Swazi',
      code: '+268',
    ),
    'KM': Country(
      numCode: '174',
      alphaCode2: 'KM',
      alphaCode3: 'COM',
      name: 'Comoros',
      nationality: 'Comoran, Comorian',
      code: '+269',
    ),
    'SH': Country(
      numCode: '654',
      alphaCode2: 'SH',
      alphaCode3: 'SHN',
      name: 'Saint Helena, Ascension and Tristan da Cunha',
      nationality: 'Saint Helenian',
      code: '+290',
    ),
    'ER': Country(
      numCode: '232',
      alphaCode2: 'ER',
      alphaCode3: 'ERI',
      name: 'Eritrea',
      nationality: 'Eritrean',
      code: '+291',
    ),
    'AW': Country(
      numCode: '533',
      alphaCode2: 'AW',
      alphaCode3: 'ABW',
      name: 'Aruba',
      nationality: 'Aruban',
      code: '+297',
    ),
    'FO': Country(
      numCode: '234',
      alphaCode2: 'FO',
      alphaCode3: 'FRO',
      name: 'Faroe Islands',
      nationality: 'Faroese',
      code: '+298',
    ),
    'GL': Country(
      numCode: '304',
      alphaCode2: 'GL',
      alphaCode3: 'GRL',
      name: 'Greenland',
      nationality: 'Greenlandic',
      code: '+299',
    ),
    'GI': Country(
      numCode: '292',
      alphaCode2: 'GI',
      alphaCode3: 'GIB',
      name: 'Gibraltar',
      nationality: 'Gibraltar',
      code: '+350',
    ),
    'PT': Country(
      numCode: '620',
      alphaCode2: 'PT',
      alphaCode3: 'PRT',
      name: 'Portugal',
      nationality: 'Portuguese',
      code: '+351',
      stripe: true,
    ),
    'LU': Country(
      numCode: '442',
      alphaCode2: 'LU',
      alphaCode3: 'LUX',
      name: 'Luxembourg',
      nationality: 'Luxembourg, Luxembourgish',
      code: '+352',
      stripe: true,
    ),
    'IE': Country(
      numCode: '372',
      alphaCode2: 'IE',
      alphaCode3: 'IRL',
      name: 'Ireland',
      nationality: 'Irish',
      code: '+353',
      stripe: true,
    ),
    'IS': Country(
      numCode: '352',
      alphaCode2: 'IS',
      alphaCode3: 'ISL',
      name: 'Iceland',
      nationality: 'Icelandic',
      code: '+354',
    ),
    'AL': Country(
      numCode: '8',
      alphaCode2: 'AL',
      alphaCode3: 'ALB',
      name: 'Albania',
      nationality: 'Albanian',
      code: '+355',
    ),
    'MT': Country(
      numCode: '470',
      alphaCode2: 'MT',
      alphaCode3: 'MLT',
      name: 'Malta',
      nationality: 'Maltese',
      code: '+356',
      stripe: true,
    ),
    'CY': Country(
      numCode: '196',
      alphaCode2: 'CY',
      alphaCode3: 'CYP',
      name: 'Cyprus',
      nationality: 'Cypriot',
      code: '+357',
      stripe: true,
    ),
    'FI': Country(
      numCode: '246',
      alphaCode2: 'FI',
      alphaCode3: 'FIN',
      name: 'Finland',
      nationality: 'Finnish',
      code: '+358',
      stripe: true,
    ),
    'BG': Country(
      numCode: '100',
      alphaCode2: 'BG',
      alphaCode3: 'BGR',
      name: 'Bulgaria',
      nationality: 'Bulgarian',
      code: '+359',
      stripe: true,
    ),
    'LT': Country(
      numCode: '440',
      alphaCode2: 'LT',
      alphaCode3: 'LTU',
      name: 'Lithuania',
      nationality: 'Lithuanian',
      code: '+370',
      stripe: true,
    ),
    'LV': Country(
      numCode: '428',
      alphaCode2: 'LV',
      alphaCode3: 'LVA',
      name: 'Latvia',
      nationality: 'Latvian',
      code: '+371',
      stripe: true,
    ),
    'EE': Country(
      numCode: '233',
      alphaCode2: 'EE',
      alphaCode3: 'EST',
      name: 'Estonia',
      nationality: 'Estonian',
      code: '+372',
      stripe: true,
    ),
    'MD': Country(
      numCode: '498',
      alphaCode2: 'MD',
      alphaCode3: 'MDA',
      name: 'Moldova (Republic of)',
      nationality: 'Moldovan',
      code: '+373',
    ),
    'AM': Country(
      numCode: '51',
      alphaCode2: 'AM',
      alphaCode3: 'ARM',
      name: 'Armenia',
      nationality: 'Armenian',
      code: '+374',
    ),
    'BY': Country(
      numCode: '112',
      alphaCode2: 'BY',
      alphaCode3: 'BLR',
      name: 'Belarus',
      nationality: 'Belarusian',
      code: '+375',
    ),
    'AD': Country(
      numCode: '20',
      alphaCode2: 'AD',
      alphaCode3: 'AND',
      name: 'Andorra',
      nationality: 'Andorran',
      code: '+376',
    ),
    'MC': Country(
      numCode: '492',
      alphaCode2: 'MC',
      alphaCode3: 'MCO',
      name: 'Monaco',
      nationality: 'Monégasque, Monacan',
      code: '+377',
    ),
    'SM': Country(
      numCode: '674',
      alphaCode2: 'SM',
      alphaCode3: 'SMR',
      name: 'San Marino',
      nationality: 'Sammarinese',
      code: '+378',
    ),
    'VA': Country(
      numCode: '336',
      alphaCode2: 'VA',
      alphaCode3: 'VAT',
      name: 'Vatican City State',
      nationality: 'Vatican',
      code: '+379',
    ),
    'UA': Country(
      numCode: '804',
      alphaCode2: 'UA',
      alphaCode3: 'UKR',
      name: 'Ukraine',
      nationality: 'Ukrainian',
      code: '+380',
    ),
    'RS': Country(
      numCode: '688',
      alphaCode2: 'RS',
      alphaCode3: 'SRB',
      name: 'Serbia',
      nationality: 'Serbian',
      code: '+381',
    ),
    'ME': Country(
      numCode: '499',
      alphaCode2: 'ME',
      alphaCode3: 'MNE',
      name: 'Montenegro',
      nationality: 'Montenegrin',
      code: '+382',
    ),
    'HR': Country(
      numCode: '191',
      alphaCode2: 'HR',
      alphaCode3: 'HRV',
      name: 'Croatia',
      nationality: 'Croatian',
      code: '+385',
    ),
    'SI': Country(
      numCode: '705',
      alphaCode2: 'SI',
      alphaCode3: 'SVN',
      name: 'Slovenia',
      nationality: 'Slovenian, Slovene',
      code: '+386',
      stripe: true,
    ),
    'BA': Country(
      numCode: '70',
      alphaCode2: 'BA',
      alphaCode3: 'BIH',
      name: 'Bosnia and Herzegovina',
      nationality: 'Bosnian or Herzegovinian',
      code: '+387',
    ),
    'MK': Country(
      numCode: '807',
      alphaCode2: 'MK',
      alphaCode3: 'MKD',
      name: 'Macedonia (the former Yugoslav Republic of)',
      nationality: 'Macedonian',
      code: '+389',
    ),
    'CZ': Country(
      numCode: '203',
      alphaCode2: 'CZ',
      alphaCode3: 'CZE',
      name: 'Czech Republic',
      nationality: 'Czech',
      code: '+420',
      stripe: true,
    ),
    'SK': Country(
      numCode: '703',
      alphaCode2: 'SK',
      alphaCode3: 'SVK',
      name: 'Slovakia',
      nationality: 'Slovak',
      code: '+421',
      stripe: true,
    ),
    'LI': Country(
      numCode: '438',
      alphaCode2: 'LI',
      alphaCode3: 'LIE',
      name: 'Liechtenstein',
      nationality: 'Liechtenstein',
      code: '+423',
    ),
    'GS': Country(
      numCode: '239',
      alphaCode2: 'GS',
      alphaCode3: 'SGS',
      name: 'South Georgia and the South Sandwich Islands',
      nationality: 'South Georgia or South Sandwich Islands',
      code: '+500',
    ),
    'BZ': Country(
      numCode: '84',
      alphaCode2: 'BZ',
      alphaCode3: 'BLZ',
      name: 'Belize',
      nationality: 'Belizean',
      code: '+501',
    ),
    'GT': Country(
      numCode: '320',
      alphaCode2: 'GT',
      alphaCode3: 'GTM',
      name: 'Guatemala',
      nationality: 'Guatemalan',
      code: '+502',
    ),
    'SV': Country(
      numCode: '222',
      alphaCode2: 'SV',
      alphaCode3: 'SLV',
      name: 'El Salvador',
      nationality: 'Salvadoran',
      code: '+503',
    ),
    'HN': Country(
      numCode: '340',
      alphaCode2: 'HN',
      alphaCode3: 'HND',
      name: 'Honduras',
      nationality: 'Honduran',
      code: '+504',
    ),
    'NI': Country(
      numCode: '558',
      alphaCode2: 'NI',
      alphaCode3: 'NIC',
      name: 'Nicaragua',
      nationality: 'Nicaraguan',
      code: '+505',
    ),
    'CR': Country(
      numCode: '188',
      alphaCode2: 'CR',
      alphaCode3: 'CRI',
      name: 'Costa Rica',
      nationality: 'Costa Rican',
      code: '+506',
    ),
    'PA': Country(
      numCode: '591',
      alphaCode2: 'PA',
      alphaCode3: 'PAN',
      name: 'Panama',
      nationality: 'Panamanian',
      code: '+507',
    ),
    'PM': Country(
      numCode: '666',
      alphaCode2: 'PM',
      alphaCode3: 'SPM',
      name: 'Saint Pierre and Miquelon',
      nationality: 'Saint-Pierrais or Miquelonnais',
      code: '+508',
    ),
    'HT': Country(
      numCode: '332',
      alphaCode2: 'HT',
      alphaCode3: 'HTI',
      name: 'Haiti',
      nationality: 'Haitian',
      code: '+509',
    ),
    'MF': Country(
      numCode: '663',
      alphaCode2: 'MF',
      alphaCode3: 'MAF',
      name: 'Saint Martin (French part)',
      nationality: 'Saint-Martinoise',
      code: '+590',
    ),
    'BO': Country(
      numCode: '68',
      alphaCode2: 'BO',
      alphaCode3: 'BOL',
      name: 'Bolivia (Plurinational State of)',
      nationality: 'Bolivian',
      code: '+591',
    ),
    'GY': Country(
      numCode: '328',
      alphaCode2: 'GY',
      alphaCode3: 'GUY',
      name: 'Guyana',
      nationality: 'Guyanese',
      code: '+592',
    ),
    'EC': Country(
      numCode: '218',
      alphaCode2: 'EC',
      alphaCode3: 'ECU',
      name: 'Ecuador',
      nationality: 'Ecuadorian',
      code: '+593',
    ),
    'GF': Country(
      numCode: '254',
      alphaCode2: 'GF',
      alphaCode3: 'GUF',
      name: 'French Guiana',
      nationality: 'French Guianese',
      code: '+594',
    ),
    'PY': Country(
      numCode: '600',
      alphaCode2: 'PY',
      alphaCode3: 'PRY',
      name: 'Paraguay',
      nationality: 'Paraguayan',
      code: '+595',
    ),
    'MQ': Country(
      numCode: '474',
      alphaCode2: 'MQ',
      alphaCode3: 'MTQ',
      name: 'Martinique',
      nationality: 'Martiniquais, Martinican',
      code: '+596',
    ),
    'SR': Country(
      numCode: '740',
      alphaCode2: 'SR',
      alphaCode3: 'SUR',
      name: 'Suriname',
      nationality: 'Surinamese',
      code: '+597',
    ),
    'UY': Country(
      numCode: '858',
      alphaCode2: 'UY',
      alphaCode3: 'URY',
      name: 'Uruguay',
      nationality: 'Uruguayan',
      code: '+598',
    ),
    'TL': Country(
      numCode: '626',
      alphaCode2: 'TL',
      alphaCode3: 'TLS',
      name: 'Timor-Leste',
      nationality: 'Timorese',
      code: '+670',
    ),
    'NF': Country(
      numCode: '574',
      alphaCode2: 'NF',
      alphaCode3: 'NFK',
      name: 'Norfolk Island',
      nationality: 'Norfolk Island',
      code: '+672',
    ),
    'BN': Country(
      numCode: '96',
      alphaCode2: 'BN',
      alphaCode3: 'BRN',
      name: 'Brunei Darussalam',
      nationality: 'Bruneian',
      code: '+673',
    ),
    'NR': Country(
      numCode: '520',
      alphaCode2: 'NR',
      alphaCode3: 'NRU',
      name: 'Nauru',
      nationality: 'Nauruan',
      code: '+674',
    ),
    'PG': Country(
      numCode: '598',
      alphaCode2: 'PG',
      alphaCode3: 'PNG',
      name: 'Papua New Guinea',
      nationality: 'Papua New Guinean, Papuan',
      code: '+675',
    ),
    'TO': Country(
      numCode: '776',
      alphaCode2: 'TO',
      alphaCode3: 'TON',
      name: 'Tonga',
      nationality: 'Tongan',
      code: '+676',
    ),
    'SB': Country(
      numCode: '90',
      alphaCode2: 'SB',
      alphaCode3: 'SLB',
      name: 'Solomon Islands',
      nationality: 'Solomon Island',
      code: '+677',
    ),
    'VU': Country(
      numCode: '548',
      alphaCode2: 'VU',
      alphaCode3: 'VUT',
      name: 'Vanuatu',
      nationality: 'Ni-Vanuatu, Vanuatuan',
      code: '+678',
    ),
    'FJ': Country(
      numCode: '242',
      alphaCode2: 'FJ',
      alphaCode3: 'FJI',
      name: 'Fiji',
      nationality: 'Fijian',
      code: '+679',
    ),
    'PW': Country(
      numCode: '585',
      alphaCode2: 'PW',
      alphaCode3: 'PLW',
      name: 'Palau',
      nationality: 'Palauan',
      code: '+680',
    ),
    'WF': Country(
      numCode: '876',
      alphaCode2: 'WF',
      alphaCode3: 'WLF',
      name: 'Wallis and Futuna',
      nationality: 'Wallis and Futuna, Wallisian or Futunan',
      code: '+681',
    ),
    'CK': Country(
      numCode: '184',
      alphaCode2: 'CK',
      alphaCode3: 'COK',
      name: 'Cook Islands',
      nationality: 'Cook Island',
      code: '+682',
    ),
    'NU': Country(
      numCode: '570',
      alphaCode2: 'NU',
      alphaCode3: 'NIU',
      name: 'Niue',
      nationality: 'Niuean',
      code: '+683',
    ),
    'WS': Country(
      numCode: '882',
      alphaCode2: 'WS',
      alphaCode3: 'WSM',
      name: 'Samoa',
      nationality: 'Samoan',
      code: '+685',
    ),
    'KI': Country(
      numCode: '296',
      alphaCode2: 'KI',
      alphaCode3: 'KIR',
      name: 'Kiribati',
      nationality: 'I-Kiribati',
      code: '+686',
    ),
    'NC': Country(
      numCode: '540',
      alphaCode2: 'NC',
      alphaCode3: 'NCL',
      name: 'New Caledonia',
      nationality: 'New Caledonian',
      code: '+687',
    ),
    'TV': Country(
      numCode: '798',
      alphaCode2: 'TV',
      alphaCode3: 'TUV',
      name: 'Tuvalu',
      nationality: 'Tuvaluan',
      code: '+688',
    ),
    'PF': Country(
      numCode: '258',
      alphaCode2: 'PF',
      alphaCode3: 'PYF',
      name: 'French Polynesia',
      nationality: 'French Polynesian',
      code: '+689',
    ),
    'TK': Country(
      numCode: '772',
      alphaCode2: 'TK',
      alphaCode3: 'TKL',
      name: 'Tokelau',
      nationality: 'Tokelauan',
      code: '+690',
    ),
    'FM': Country(
      numCode: '583',
      alphaCode2: 'FM',
      alphaCode3: 'FSM',
      name: 'Micronesia (Federated States of)',
      nationality: 'Micronesian',
      code: '+691',
    ),
    'MH': Country(
      numCode: '584',
      alphaCode2: 'MH',
      alphaCode3: 'MHL',
      name: 'Marshall Islands',
      nationality: 'Marshallese',
      code: '+692',
    ),
    'KP': Country(
      numCode: '408',
      alphaCode2: 'KP',
      alphaCode3: 'PRK',
      name: 'Korea (Democratic People\'s Republic of)',
      nationality: 'North Korean',
      code: '+850',
    ),
    'HK': Country(
      numCode: '344',
      alphaCode2: 'HK',
      alphaCode3: 'HKG',
      name: 'Hong Kong',
      nationality: 'Hong Kong, Hong Kongese',
      code: '+852',
      stripe: true,
    ),
    'MO': Country(
      numCode: '446',
      alphaCode2: 'MO',
      alphaCode3: 'MAC',
      name: 'Macao',
      nationality: 'Macanese, Chinese',
      code: '+853',
    ),
    'KH': Country(
      numCode: '116',
      alphaCode2: 'KH',
      alphaCode3: 'KHM',
      name: 'Cambodia',
      nationality: 'Cambodian',
      code: '+855',
    ),
    'LA': Country(
      numCode: '418',
      alphaCode2: 'LA',
      alphaCode3: 'LAO',
      name: 'Lao People\'s Democratic Republic',
      nationality: 'Lao, Laotian',
      code: '+856',
    ),
    'BD': Country(
      numCode: '50',
      alphaCode2: 'BD',
      alphaCode3: 'BGD',
      name: 'Bangladesh',
      nationality: 'Bangladeshi',
      code: '+880',
    ),
    'TW': Country(
      numCode: '158',
      alphaCode2: 'TW',
      alphaCode3: 'TWN',
      name: 'Taiwan, Province of China',
      nationality: 'Chinese, Taiwanese',
      code: '+886',
    ),
    'MV': Country(
      numCode: '462',
      alphaCode2: 'MV',
      alphaCode3: 'MDV',
      name: 'Maldives',
      nationality: 'Maldivian',
      code: '+960',
    ),
    'LB': Country(
      numCode: '422',
      alphaCode2: 'LB',
      alphaCode3: 'LBN',
      name: 'Lebanon',
      nationality: 'Lebanese',
      code: '+961',
    ),
    'JO': Country(
      numCode: '400',
      alphaCode2: 'JO',
      alphaCode3: 'JOR',
      name: 'Jordan',
      nationality: 'Jordanian',
      code: '+962',
    ),
    'SY': Country(
      numCode: '760',
      alphaCode2: 'SY',
      alphaCode3: 'SYR',
      name: 'Syrian Arab Republic',
      nationality: 'Syrian',
      code: '+963',
    ),
    'IQ': Country(
      numCode: '368',
      alphaCode2: 'IQ',
      alphaCode3: 'IRQ',
      name: 'Iraq',
      nationality: 'Iraqi',
      code: '+964',
    ),
    'KW': Country(
      numCode: '414',
      alphaCode2: 'KW',
      alphaCode3: 'KWT',
      name: 'Kuwait',
      nationality: 'Kuwaiti',
      code: '+965',
    ),
    'SA': Country(
      numCode: '682',
      alphaCode2: 'SA',
      alphaCode3: 'SAU',
      name: 'Saudi Arabia',
      nationality: 'Saudi, Saudi Arabian',
      code: '+966',
    ),
    'YE': Country(
      numCode: '887',
      alphaCode2: 'YE',
      alphaCode3: 'YEM',
      name: 'Yemen',
      nationality: 'Yemeni',
      code: '+967',
    ),
    'OM': Country(
      numCode: '512',
      alphaCode2: 'OM',
      alphaCode3: 'OMN',
      name: 'Oman',
      nationality: 'Omani',
      code: '+968',
    ),
    'PS': Country(
      numCode: '275',
      alphaCode2: 'PS',
      alphaCode3: 'PSE',
      name: 'Palestine, State of',
      nationality: 'Palestinian',
      code: '+970',
    ),
    'AE': Country(
      numCode: '784',
      alphaCode2: 'AE',
      alphaCode3: 'ARE',
      name: 'United Arab Emirates',
      nationality: 'Emirati, Emirian, Emiri',
      code: '+971',
    ),
    'IL': Country(
      numCode: '376',
      alphaCode2: 'IL',
      alphaCode3: 'ISR',
      name: 'Israel',
      nationality: 'Israeli',
      code: '+972',
    ),
    'BH': Country(
      numCode: '48',
      alphaCode2: 'BH',
      alphaCode3: 'BHR',
      name: 'Bahrain',
      nationality: 'Bahraini',
      code: '+973',
    ),
    'QA': Country(
      numCode: '634',
      alphaCode2: 'QA',
      alphaCode3: 'QAT',
      name: 'Qatar',
      nationality: 'Qatari',
      code: '+974',
    ),
    'BT': Country(
      numCode: '64',
      alphaCode2: 'BT',
      alphaCode3: 'BTN',
      name: 'Bhutan',
      nationality: 'Bhutanese',
      code: '+975',
    ),
    'MN': Country(
      numCode: '496',
      alphaCode2: 'MN',
      alphaCode3: 'MNG',
      name: 'Mongolia',
      nationality: 'Mongolian',
      code: '+976',
    ),
    'NP': Country(
      numCode: '524',
      alphaCode2: 'NP',
      alphaCode3: 'NPL',
      name: 'Nepal',
      nationality: 'Nepali, Nepalese',
      code: '+977',
    ),
    'TJ': Country(
      numCode: '762',
      alphaCode2: 'TJ',
      alphaCode3: 'TJK',
      name: 'Tajikistan',
      nationality: 'Tajikistani',
      code: '+992',
    ),
    'TM': Country(
      numCode: '795',
      alphaCode2: 'TM',
      alphaCode3: 'TKM',
      name: 'Turkmenistan',
      nationality: 'Turkmen',
      code: '+993',
    ),
    'AZ': Country(
      numCode: '31',
      alphaCode2: 'AZ',
      alphaCode3: 'AZE',
      name: 'Azerbaijan',
      nationality: 'Azerbaijani, Azeri',
      code: '+994',
    ),
    'GE': Country(
      numCode: '268',
      alphaCode2: 'GE',
      alphaCode3: 'GEO',
      name: 'Georgia',
      nationality: 'Georgian',
      code: '+995',
    ),
    'KG': Country(
      numCode: '417',
      alphaCode2: 'KG',
      alphaCode3: 'KGZ',
      name: 'Kyrgyzstan',
      nationality: 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz',
      code: '+996',
    ),
    'UZ': Country(
      numCode: '860',
      alphaCode2: 'UZ',
      alphaCode3: 'UZB',
      name: 'Uzbekistan',
      nationality: 'Uzbekistani, Uzbek',
      code: '+998',
    ),
    'BS': Country(
      numCode: '44',
      alphaCode2: 'BS',
      alphaCode3: 'BHS',
      name: 'Bahamas',
      nationality: 'Bahamian',
      code: '+1242',
    ),
    'BB': Country(
      numCode: '52',
      alphaCode2: 'BB',
      alphaCode3: 'BRB',
      name: 'Barbados',
      nationality: 'Barbadian',
      code: '+1246',
    ),
    'AI': Country(
      numCode: '660',
      alphaCode2: 'AI',
      alphaCode3: 'AIA',
      name: 'Anguilla',
      nationality: 'Anguillan',
      code: '+1264',
    ),
    'AG': Country(
      numCode: '28',
      alphaCode2: 'AG',
      alphaCode3: 'ATG',
      name: 'Antigua and Barbuda',
      nationality: 'Antiguan or Barbudan',
      code: '+1268',
    ),
    'VG': Country(
      numCode: '92',
      alphaCode2: 'VG',
      alphaCode3: 'VGB',
      name: 'Virgin Islands (British)',
      nationality: 'British Virgin Island',
      code: '+1284',
    ),
    'VI': Country(
      numCode: '850',
      alphaCode2: 'VI',
      alphaCode3: 'VIR',
      name: 'Virgin Islands (U.S.)',
      nationality: 'U.S. Virgin Island',
      code: '+1340',
    ),
    'KY': Country(
      numCode: '136',
      alphaCode2: 'KY',
      alphaCode3: 'CYM',
      name: 'Cayman Islands',
      nationality: 'Caymanian',
      code: '+1345',
    ),
    'BM': Country(
      numCode: '60',
      alphaCode2: 'BM',
      alphaCode3: 'BMU',
      name: 'Bermuda',
      nationality: 'Bermudian, Bermudan',
      code: '+1441',
    ),
    'GD': Country(
      numCode: '308',
      alphaCode2: 'GD',
      alphaCode3: 'GRD',
      name: 'Grenada',
      nationality: 'Grenadian',
      code: '+1473',
    ),
    'TC': Country(
      numCode: '796',
      alphaCode2: 'TC',
      alphaCode3: 'TCA',
      name: 'Turks and Caicos Islands',
      nationality: 'Turks and Caicos Island',
      code: '+1649',
    ),
    'MS': Country(
      numCode: '500',
      alphaCode2: 'MS',
      alphaCode3: 'MSR',
      name: 'Montserrat',
      nationality: 'Montserratian',
      code: '+1664',
    ),
    'MP': Country(
      numCode: '580',
      alphaCode2: 'MP',
      alphaCode3: 'MNP',
      name: 'Northern Mariana Islands',
      nationality: 'Northern Marianan',
      code: '+1670',
    ),
    'GU': Country(
      numCode: '316',
      alphaCode2: 'GU',
      alphaCode3: 'GUM',
      name: 'Guam',
      nationality: 'Guamanian, Guambat',
      code: '+1671',
    ),
    'AS': Country(
      numCode: '16',
      alphaCode2: 'AS',
      alphaCode3: 'ASM',
      name: 'American Samoa',
      nationality: 'American Samoan',
      code: '+1684',
    ),
    'LC': Country(
      numCode: '662',
      alphaCode2: 'LC',
      alphaCode3: 'LCA',
      name: 'Saint Lucia',
      nationality: 'Saint Lucian',
      code: '+1758',
    ),
    'DM': Country(
      numCode: '212',
      alphaCode2: 'DM',
      alphaCode3: 'DMA',
      name: 'Dominica',
      nationality: 'Dominican',
      code: '+1767',
    ),
    'VC': Country(
      numCode: '670',
      alphaCode2: 'VC',
      alphaCode3: 'VCT',
      name: 'Saint Vincent and the Grenadines',
      nationality: 'Saint Vincentian, Vincentian',
      code: '+1784',
    ),
    'DO': Country(
      numCode: '214',
      alphaCode2: 'DO',
      alphaCode3: 'DOM',
      name: 'Dominican Republic',
      nationality: 'Dominican',
      code: '+1849',
    ),
    'TT': Country(
      numCode: '780',
      alphaCode2: 'TT',
      alphaCode3: 'TTO',
      name: 'Trinidad and Tobago',
      nationality: 'Trinidadian or Tobagonian',
      code: '+1868',
    ),
    'KN': Country(
      numCode: '659',
      alphaCode2: 'KN',
      alphaCode3: 'KNA',
      name: 'Saint Kitts and Nevis',
      nationality: 'Kittitian or Nevisian',
      code: '+1869',
    ),
    'JM': Country(
      numCode: '388',
      alphaCode2: 'JM',
      alphaCode3: 'JAM',
      name: 'Jamaica',
      nationality: 'Jamaican',
      code: '+1876',
    ),
    'PR': Country(
      numCode: '630',
      alphaCode2: 'PR',
      alphaCode3: 'PRI',
      name: 'Puerto Rico',
      nationality: 'Puerto Rican',
      code: '+1939',
    ),
  };

  static final _kCountriesByCountryCode = <String, Country>{
    '+0': _kCountries['HM'],
    '+1': _kCountries['US'],
    '+7': _kCountries['RU'],
    '+20': _kCountries['EG'],
    '+27': _kCountries['ZA'],
    '+30': _kCountries['GR'],
    '+31': _kCountries['NL'],
    '+32': _kCountries['BE'],
    '+33': _kCountries['FR'],
    '+34': _kCountries['ES'],
    '+36': _kCountries['HU'],
    '+39': _kCountries['IT'],
    '+40': _kCountries['RO'],
    '+41': _kCountries['CH'],
    '+43': _kCountries['AT'],
    '+44': _kCountries['GB'],
    '+45': _kCountries['DK'],
    '+46': _kCountries['SE'],
    '+47': _kCountries['SJ'],
    '+48': _kCountries['PL'],
    '+49': _kCountries['DE'],
    '+51': _kCountries['PE'],
    '+52': _kCountries['MX'],
    '+53': _kCountries['CU'],
    '+54': _kCountries['AR'],
    '+55': _kCountries['BR'],
    '+56': _kCountries['CL'],
    '+57': _kCountries['CO'],
    '+58': _kCountries['VE'],
    '+60': _kCountries['MY'],
    '+61': _kCountries['CC'],
    '+62': _kCountries['ID'],
    '+63': _kCountries['PH'],
    '+64': _kCountries['PN'],
    '+65': _kCountries['SG'],
    '+66': _kCountries['TH'],
    '+81': _kCountries['JP'],
    '+82': _kCountries['KR'],
    '+84': _kCountries['VN'],
    '+86': _kCountries['CN'],
    '+90': _kCountries['TR'],
    '+91': _kCountries['IN'],
    '+92': _kCountries['PK'],
    '+93': _kCountries['AF'],
    '+94': _kCountries['LK'],
    '+95': _kCountries['MM'],
    '+98': _kCountries['IR'],
    '+211': _kCountries['SS'],
    '+212': _kCountries['MA'],
    '+213': _kCountries['DZ'],
    '+216': _kCountries['TN'],
    '+218': _kCountries['LY'],
    '+220': _kCountries['GM'],
    '+221': _kCountries['SN'],
    '+222': _kCountries['MR'],
    '+223': _kCountries['ML'],
    '+224': _kCountries['GN'],
    '+225': _kCountries['CI'],
    '+226': _kCountries['BF'],
    '+227': _kCountries['NE'],
    '+228': _kCountries['TG'],
    '+229': _kCountries['BJ'],
    '+230': _kCountries['MU'],
    '+231': _kCountries['LR'],
    '+232': _kCountries['SL'],
    '+233': _kCountries['GH'],
    '+234': _kCountries['NG'],
    '+235': _kCountries['TD'],
    '+236': _kCountries['CF'],
    '+237': _kCountries['CM'],
    '+238': _kCountries['CV'],
    '+239': _kCountries['ST'],
    '+240': _kCountries['GQ'],
    '+241': _kCountries['GA'],
    '+242': _kCountries['CG'],
    '+243': _kCountries['CD'],
    '+244': _kCountries['AO'],
    '+245': _kCountries['GW'],
    '+246': _kCountries['IO'],
    '+248': _kCountries['SC'],
    '+249': _kCountries['SD'],
    '+250': _kCountries['RW'],
    '+251': _kCountries['ET'],
    '+252': _kCountries['SO'],
    '+253': _kCountries['DJ'],
    '+254': _kCountries['KE'],
    '+255': _kCountries['TZ'],
    '+256': _kCountries['UG'],
    '+257': _kCountries['BI'],
    '+258': _kCountries['MZ'],
    '+260': _kCountries['ZM'],
    '+261': _kCountries['MG'],
    '+262': _kCountries['RE'],
    '+263': _kCountries['ZW'],
    '+264': _kCountries['NA'],
    '+265': _kCountries['MW'],
    '+266': _kCountries['LS'],
    '+267': _kCountries['BW'],
    '+268': _kCountries['SZ'],
    '+269': _kCountries['KM'],
    '+290': _kCountries['SH'],
    '+291': _kCountries['ER'],
    '+297': _kCountries['AW'],
    '+298': _kCountries['FO'],
    '+299': _kCountries['GL'],
    '+350': _kCountries['GI'],
    '+351': _kCountries['PT'],
    '+352': _kCountries['LU'],
    '+353': _kCountries['IE'],
    '+354': _kCountries['IS'],
    '+355': _kCountries['AL'],
    '+356': _kCountries['MT'],
    '+357': _kCountries['CY'],
    '+358': _kCountries['FI'],
    '+359': _kCountries['BG'],
    '+370': _kCountries['LT'],
    '+371': _kCountries['LV'],
    '+372': _kCountries['EE'],
    '+373': _kCountries['MD'],
    '+374': _kCountries['AM'],
    '+375': _kCountries['BY'],
    '+376': _kCountries['AD'],
    '+377': _kCountries['MC'],
    '+378': _kCountries['SM'],
    '+379': _kCountries['VA'],
    '+380': _kCountries['UA'],
    '+381': _kCountries['RS'],
    '+382': _kCountries['ME'],
    '+385': _kCountries['HR'],
    '+386': _kCountries['SI'],
    '+387': _kCountries['BA'],
    '+389': _kCountries['MK'],
    '+420': _kCountries['CZ'],
    '+421': _kCountries['SK'],
    '+423': _kCountries['LI'],
    '+500': _kCountries['GS'],
    '+501': _kCountries['BZ'],
    '+502': _kCountries['GT'],
    '+503': _kCountries['SV'],
    '+504': _kCountries['HN'],
    '+505': _kCountries['NI'],
    '+506': _kCountries['CR'],
    '+507': _kCountries['PA'],
    '+508': _kCountries['PM'],
    '+509': _kCountries['HT'],
    '+590': _kCountries['MF'],
    '+591': _kCountries['BO'],
    '+592': _kCountries['GY'],
    '+593': _kCountries['EC'],
    '+594': _kCountries['GF'],
    '+595': _kCountries['PY'],
    '+596': _kCountries['MQ'],
    '+597': _kCountries['SR'],
    '+598': _kCountries['UY'],
    '+670': _kCountries['TL'],
    '+672': _kCountries['NF'],
    '+673': _kCountries['BN'],
    '+674': _kCountries['NR'],
    '+675': _kCountries['PG'],
    '+676': _kCountries['TO'],
    '+677': _kCountries['SB'],
    '+678': _kCountries['VU'],
    '+679': _kCountries['FJ'],
    '+680': _kCountries['PW'],
    '+681': _kCountries['WF'],
    '+682': _kCountries['CK'],
    '+683': _kCountries['NU'],
    '+685': _kCountries['WS'],
    '+686': _kCountries['KI'],
    '+687': _kCountries['NC'],
    '+688': _kCountries['TV'],
    '+689': _kCountries['PF'],
    '+690': _kCountries['TK'],
    '+691': _kCountries['FM'],
    '+692': _kCountries['MH'],
    '+850': _kCountries['KP'],
    '+852': _kCountries['HK'],
    '+853': _kCountries['MO'],
    '+855': _kCountries['KH'],
    '+856': _kCountries['LA'],
    '+880': _kCountries['BD'],
    '+886': _kCountries['TW'],
    '+960': _kCountries['MV'],
    '+961': _kCountries['LB'],
    '+962': _kCountries['JO'],
    '+963': _kCountries['SY'],
    '+964': _kCountries['IQ'],
    '+965': _kCountries['KW'],
    '+966': _kCountries['SA'],
    '+967': _kCountries['YE'],
    '+968': _kCountries['OM'],
    '+970': _kCountries['PS'],
    '+971': _kCountries['AE'],
    '+972': _kCountries['IL'],
    '+973': _kCountries['BH'],
    '+974': _kCountries['QA'],
    '+975': _kCountries['BT'],
    '+976': _kCountries['MN'],
    '+977': _kCountries['NP'],
    '+992': _kCountries['TJ'],
    '+993': _kCountries['TM'],
    '+994': _kCountries['AZ'],
    '+995': _kCountries['GE'],
    '+996': _kCountries['KG'],
    '+998': _kCountries['UZ'],
    '+1242': _kCountries['BS'],
    '+1246': _kCountries['BB'],
    '+1264': _kCountries['AI'],
    '+1268': _kCountries['AG'],
    '+1284': _kCountries['VG'],
    '+1340': _kCountries['VI'],
    '+1345': _kCountries['KY'],
    '+1441': _kCountries['BM'],
    '+1473': _kCountries['GD'],
    '+1649': _kCountries['TC'],
    '+1664': _kCountries['MS'],
    '+1670': _kCountries['MP'],
    '+1671': _kCountries['GU'],
    '+1684': _kCountries['AS'],
    '+1758': _kCountries['LC'],
    '+1767': _kCountries['DM'],
    '+1784': _kCountries['VC'],
    '+1849': _kCountries['DO'],
    '+1868': _kCountries['TT'],
    '+1869': _kCountries['KN'],
    '+1876': _kCountries['JM'],
    '+1939': _kCountries['PR'],
  };
}
